sonar.projectKey=ssd-practical
sonar.projectName=SSD Practical Test
sonar.sources=web
sonar.exclusions=web/tests/**,**/__pycache__/**
sonar.tests=web/tests
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
